// ============================================================
// WA-Bridge — International calling-code directory
//
// Country calling codes are based on the ITU-T E.164 numbering plan.
// This is intentionally dependency-free: pairing only needs to reject
// impossible prefixes and explain the accepted international format.
// ============================================================

export interface CountryCallingCode {
  code: string;
  countries: string;
  region: 'Africa' | 'Americas' | 'Asia' | 'Europe' | 'Oceania' | 'Middle East';
}

/** Assigned geographic country/territory calling codes. */
export const COUNTRY_CALLING_CODES: readonly CountryCallingCode[] = [
  // Non-geographic E.164 service ranges accepted by international routing.
  { code: '800', countries: 'International Freephone Service', region: 'Europe' },
  { code: '808', countries: 'International Shared Cost Service', region: 'Europe' },
  { code: '870', countries: 'Inmarsat', region: 'Oceania' },
  { code: '878', countries: 'Universal Personal Telecommunication', region: 'Europe' },
  { code: '881', countries: 'Global Mobile Satellite System', region: 'Oceania' },
  { code: '882', countries: 'International Networks', region: 'Europe' },
  { code: '883', countries: 'International Networks', region: 'Europe' },
  { code: '888', countries: 'UN OCHA Humanitarian Telecommunications', region: 'Europe' },
  // Africa
  { code: '20', countries: 'Egypt', region: 'Africa' },
  { code: '211', countries: 'South Sudan', region: 'Africa' },
  { code: '212', countries: 'Morocco, Western Sahara', region: 'Africa' },
  { code: '213', countries: 'Algeria', region: 'Africa' },
  { code: '216', countries: 'Tunisia', region: 'Africa' },
  { code: '218', countries: 'Libya', region: 'Africa' },
  { code: '220', countries: 'Gambia', region: 'Africa' },
  { code: '221', countries: 'Senegal', region: 'Africa' },
  { code: '222', countries: 'Mauritania', region: 'Africa' },
  { code: '223', countries: 'Mali', region: 'Africa' },
  { code: '224', countries: 'Guinea', region: 'Africa' },
  { code: '225', countries: 'Côte d’Ivoire', region: 'Africa' },
  { code: '226', countries: 'Burkina Faso', region: 'Africa' },
  { code: '227', countries: 'Niger', region: 'Africa' },
  { code: '228', countries: 'Togo', region: 'Africa' },
  { code: '229', countries: 'Benin', region: 'Africa' },
  { code: '230', countries: 'Mauritius', region: 'Africa' },
  { code: '231', countries: 'Liberia', region: 'Africa' },
  { code: '232', countries: 'Sierra Leone', region: 'Africa' },
  { code: '233', countries: 'Ghana', region: 'Africa' },
  { code: '234', countries: 'Nigeria', region: 'Africa' },
  { code: '235', countries: 'Chad', region: 'Africa' },
  { code: '236', countries: 'Central African Republic', region: 'Africa' },
  { code: '237', countries: 'Cameroon', region: 'Africa' },
  { code: '238', countries: 'Cabo Verde', region: 'Africa' },
  { code: '239', countries: 'São Tomé and Príncipe', region: 'Africa' },
  { code: '240', countries: 'Equatorial Guinea', region: 'Africa' },
  { code: '241', countries: 'Gabon', region: 'Africa' },
  { code: '242', countries: 'Congo', region: 'Africa' },
  { code: '243', countries: 'DR Congo', region: 'Africa' },
  { code: '244', countries: 'Angola', region: 'Africa' },
  { code: '245', countries: 'Guinea-Bissau', region: 'Africa' },
  { code: '246', countries: 'British Indian Ocean Territory', region: 'Africa' },
  { code: '247', countries: 'Ascension Island', region: 'Africa' },
  { code: '248', countries: 'Seychelles', region: 'Africa' },
  { code: '249', countries: 'Sudan', region: 'Africa' },
  { code: '250', countries: 'Rwanda', region: 'Africa' },
  { code: '251', countries: 'Ethiopia', region: 'Africa' },
  { code: '252', countries: 'Somalia', region: 'Africa' },
  { code: '253', countries: 'Djibouti', region: 'Africa' },
  { code: '254', countries: 'Kenya', region: 'Africa' },
  { code: '255', countries: 'Tanzania', region: 'Africa' },
  { code: '256', countries: 'Uganda', region: 'Africa' },
  { code: '257', countries: 'Burundi', region: 'Africa' },
  { code: '258', countries: 'Mozambique', region: 'Africa' },
  { code: '260', countries: 'Zambia', region: 'Africa' },
  { code: '261', countries: 'Madagascar', region: 'Africa' },
  { code: '262', countries: 'Réunion, Mayotte', region: 'Africa' },
  { code: '263', countries: 'Zimbabwe', region: 'Africa' },
  { code: '264', countries: 'Namibia', region: 'Africa' },
  { code: '265', countries: 'Malawi', region: 'Africa' },
  { code: '266', countries: 'Lesotho', region: 'Africa' },
  { code: '267', countries: 'Botswana', region: 'Africa' },
  { code: '268', countries: 'Eswatini', region: 'Africa' },
  { code: '269', countries: 'Comoros', region: 'Africa' },
  { code: '27', countries: 'South Africa', region: 'Africa' },
  { code: '290', countries: 'Saint Helena, Tristan da Cunha', region: 'Africa' },
  { code: '291', countries: 'Eritrea', region: 'Africa' },
  { code: '297', countries: 'Aruba', region: 'Americas' },
  { code: '298', countries: 'Faroe Islands', region: 'Europe' },
  { code: '299', countries: 'Greenland', region: 'Americas' },

  // Americas and shared North American numbering plan
  { code: '1', countries: 'US, Canada, Caribbean NANP countries', region: 'Americas' },
  { code: '500', countries: 'Falkland Islands, South Georgia', region: 'Americas' },
  { code: '501', countries: 'Belize', region: 'Americas' },
  { code: '502', countries: 'Guatemala', region: 'Americas' },
  { code: '503', countries: 'El Salvador', region: 'Americas' },
  { code: '504', countries: 'Honduras', region: 'Americas' },
  { code: '505', countries: 'Nicaragua', region: 'Americas' },
  { code: '506', countries: 'Costa Rica', region: 'Americas' },
  { code: '507', countries: 'Panama', region: 'Americas' },
  { code: '508', countries: 'Saint Pierre and Miquelon', region: 'Americas' },
  { code: '509', countries: 'Haiti', region: 'Americas' },
  { code: '51', countries: 'Peru', region: 'Americas' },
  { code: '52', countries: 'Mexico', region: 'Americas' },
  { code: '53', countries: 'Cuba', region: 'Americas' },
  { code: '54', countries: 'Argentina', region: 'Americas' },
  { code: '55', countries: 'Brazil', region: 'Americas' },
  { code: '56', countries: 'Chile', region: 'Americas' },
  { code: '57', countries: 'Colombia', region: 'Americas' },
  { code: '58', countries: 'Venezuela', region: 'Americas' },
  { code: '590', countries: 'Guadeloupe, Saint Barthélemy, Saint Martin', region: 'Americas' },
  { code: '591', countries: 'Bolivia', region: 'Americas' },
  { code: '592', countries: 'Guyana', region: 'Americas' },
  { code: '593', countries: 'Ecuador', region: 'Americas' },
  { code: '594', countries: 'French Guiana', region: 'Americas' },
  { code: '595', countries: 'Paraguay', region: 'Americas' },
  { code: '596', countries: 'Martinique', region: 'Americas' },
  { code: '597', countries: 'Suriname', region: 'Americas' },
  { code: '598', countries: 'Uruguay', region: 'Americas' },
  { code: '599', countries: 'Curaçao, Caribbean Netherlands', region: 'Americas' },

  // Europe
  { code: '30', countries: 'Greece', region: 'Europe' },
  { code: '31', countries: 'Netherlands', region: 'Europe' },
  { code: '32', countries: 'Belgium', region: 'Europe' },
  { code: '33', countries: 'France', region: 'Europe' },
  { code: '34', countries: 'Spain', region: 'Europe' },
  { code: '350', countries: 'Gibraltar', region: 'Europe' },
  { code: '351', countries: 'Portugal', region: 'Europe' },
  { code: '352', countries: 'Luxembourg', region: 'Europe' },
  { code: '353', countries: 'Ireland', region: 'Europe' },
  { code: '354', countries: 'Iceland', region: 'Europe' },
  { code: '355', countries: 'Albania', region: 'Europe' },
  { code: '356', countries: 'Malta', region: 'Europe' },
  { code: '357', countries: 'Cyprus', region: 'Europe' },
  { code: '358', countries: 'Finland, Åland Islands', region: 'Europe' },
  { code: '359', countries: 'Bulgaria', region: 'Europe' },
  { code: '36', countries: 'Hungary', region: 'Europe' },
  { code: '370', countries: 'Lithuania', region: 'Europe' },
  { code: '371', countries: 'Latvia', region: 'Europe' },
  { code: '372', countries: 'Estonia', region: 'Europe' },
  { code: '373', countries: 'Moldova', region: 'Europe' },
  { code: '374', countries: 'Armenia', region: 'Asia' },
  { code: '375', countries: 'Belarus', region: 'Europe' },
  { code: '376', countries: 'Andorra', region: 'Europe' },
  { code: '377', countries: 'Monaco', region: 'Europe' },
  { code: '378', countries: 'San Marino', region: 'Europe' },
  { code: '380', countries: 'Ukraine', region: 'Europe' },
  { code: '381', countries: 'Serbia', region: 'Europe' },
  { code: '382', countries: 'Montenegro', region: 'Europe' },
  { code: '383', countries: 'Kosovo', region: 'Europe' },
  { code: '385', countries: 'Croatia', region: 'Europe' },
  { code: '386', countries: 'Slovenia', region: 'Europe' },
  { code: '387', countries: 'Bosnia and Herzegovina', region: 'Europe' },
  { code: '389', countries: 'North Macedonia', region: 'Europe' },
  { code: '39', countries: 'Italy, Vatican City', region: 'Europe' },
  { code: '40', countries: 'Romania', region: 'Europe' },
  { code: '41', countries: 'Switzerland', region: 'Europe' },
  { code: '420', countries: 'Czechia', region: 'Europe' },
  { code: '421', countries: 'Slovakia', region: 'Europe' },
  { code: '423', countries: 'Liechtenstein', region: 'Europe' },
  { code: '43', countries: 'Austria', region: 'Europe' },
  { code: '44', countries: 'United Kingdom', region: 'Europe' },
  { code: '45', countries: 'Denmark', region: 'Europe' },
  { code: '46', countries: 'Sweden', region: 'Europe' },
  { code: '47', countries: 'Norway, Svalbard', region: 'Europe' },
  { code: '48', countries: 'Poland', region: 'Europe' },
  { code: '49', countries: 'Germany', region: 'Europe' },

  // Asia and Middle East
  { code: '60', countries: 'Malaysia', region: 'Asia' },
  { code: '61', countries: 'Australia, Christmas, Cocos Islands', region: 'Oceania' },
  { code: '62', countries: 'Indonesia', region: 'Asia' },
  { code: '63', countries: 'Philippines', region: 'Asia' },
  { code: '64', countries: 'New Zealand, Pitcairn', region: 'Oceania' },
  { code: '65', countries: 'Singapore', region: 'Asia' },
  { code: '66', countries: 'Thailand', region: 'Asia' },
  { code: '670', countries: 'Timor-Leste', region: 'Asia' },
  { code: '672', countries: 'Australian External Territories', region: 'Oceania' },
  { code: '673', countries: 'Brunei', region: 'Asia' },
  { code: '674', countries: 'Nauru', region: 'Oceania' },
  { code: '675', countries: 'Papua New Guinea', region: 'Oceania' },
  { code: '676', countries: 'Tonga', region: 'Oceania' },
  { code: '677', countries: 'Solomon Islands', region: 'Oceania' },
  { code: '678', countries: 'Vanuatu', region: 'Oceania' },
  { code: '679', countries: 'Fiji', region: 'Oceania' },
  { code: '680', countries: 'Palau', region: 'Oceania' },
  { code: '681', countries: 'Wallis and Futuna', region: 'Oceania' },
  { code: '682', countries: 'Cook Islands', region: 'Oceania' },
  { code: '683', countries: 'Niue', region: 'Oceania' },
  { code: '685', countries: 'Samoa', region: 'Oceania' },
  { code: '686', countries: 'Kiribati', region: 'Oceania' },
  { code: '687', countries: 'New Caledonia', region: 'Oceania' },
  { code: '688', countries: 'Tuvalu', region: 'Oceania' },
  { code: '689', countries: 'French Polynesia', region: 'Oceania' },
  { code: '690', countries: 'Tokelau', region: 'Oceania' },
  { code: '691', countries: 'Micronesia', region: 'Oceania' },
  { code: '692', countries: 'Marshall Islands', region: 'Oceania' },
  { code: '7', countries: 'Russia, Kazakhstan', region: 'Asia' },
  { code: '81', countries: 'Japan', region: 'Asia' },
  { code: '82', countries: 'South Korea', region: 'Asia' },
  { code: '84', countries: 'Vietnam', region: 'Asia' },
  { code: '850', countries: 'North Korea', region: 'Asia' },
  { code: '852', countries: 'Hong Kong', region: 'Asia' },
  { code: '853', countries: 'Macau', region: 'Asia' },
  { code: '855', countries: 'Cambodia', region: 'Asia' },
  { code: '856', countries: 'Laos', region: 'Asia' },
  { code: '86', countries: 'China', region: 'Asia' },
  { code: '880', countries: 'Bangladesh', region: 'Asia' },
  { code: '886', countries: 'Taiwan', region: 'Asia' },
  { code: '90', countries: 'Türkiye', region: 'Middle East' },
  { code: '91', countries: 'India', region: 'Asia' },
  { code: '92', countries: 'Pakistan', region: 'Asia' },
  { code: '93', countries: 'Afghanistan', region: 'Asia' },
  { code: '94', countries: 'Sri Lanka', region: 'Asia' },
  { code: '95', countries: 'Myanmar', region: 'Asia' },
  { code: '960', countries: 'Maldives', region: 'Asia' },
  { code: '961', countries: 'Lebanon', region: 'Middle East' },
  { code: '962', countries: 'Jordan', region: 'Middle East' },
  { code: '963', countries: 'Syria', region: 'Middle East' },
  { code: '964', countries: 'Iraq', region: 'Middle East' },
  { code: '965', countries: 'Kuwait', region: 'Middle East' },
  { code: '966', countries: 'Saudi Arabia', region: 'Middle East' },
  { code: '967', countries: 'Yemen', region: 'Middle East' },
  { code: '968', countries: 'Oman', region: 'Middle East' },
  { code: '970', countries: 'Palestine', region: 'Middle East' },
  { code: '971', countries: 'United Arab Emirates', region: 'Middle East' },
  { code: '972', countries: 'Israel', region: 'Middle East' },
  { code: '973', countries: 'Bahrain', region: 'Middle East' },
  { code: '974', countries: 'Qatar', region: 'Middle East' },
  { code: '975', countries: 'Bhutan', region: 'Asia' },
  { code: '976', countries: 'Mongolia', region: 'Asia' },
  { code: '977', countries: 'Nepal', region: 'Asia' },
  { code: '98', countries: 'Iran', region: 'Middle East' },
  { code: '992', countries: 'Tajikistan', region: 'Asia' },
  { code: '993', countries: 'Turkmenistan', region: 'Asia' },
  { code: '994', countries: 'Azerbaijan', region: 'Asia' },
  { code: '995', countries: 'Georgia', region: 'Asia' },
  { code: '996', countries: 'Kyrgyzstan', region: 'Asia' },
  { code: '998', countries: 'Uzbekistan', region: 'Asia' },
];

const byCode = new Map(COUNTRY_CALLING_CODES.map((entry) => [entry.code, entry]));

/** Return the longest assigned calling-code prefix in a normalized number. */
export function findCountryCallingCode(normalizedNumber: string): CountryCallingCode | null {
  for (let length = 3; length >= 1; length--) {
    const entry = byCode.get(normalizedNumber.slice(0, length));
    if (entry) return entry;
  }
  return null;
}

/** Compact, WhatsApp-friendly directory shown by `.pair codes`. */
export function formatCountryCodeGuide(): string {
  const regions: CountryCallingCode['region'][] = ['Africa', 'Americas', 'Europe', 'Asia', 'Middle East', 'Oceania'];
  const lines = regions.map((region) => {
    const entries = COUNTRY_CALLING_CODES
      .filter((entry) => entry.region === region)
      .map((entry) => `+${entry.code} ${entry.countries}`);
    return `${region}\n${entries.join(' · ')}`;
  });
  return [
    'Use the international format: +[country code][number].',
    'Spaces, hyphens and parentheses are accepted and removed automatically.',
    'Never start with +0 — 0 is not an assigned country-code prefix.',
    'The directory includes geographic and common non-geographic E.164 prefixes; WhatsApp still decides whether the full number is active.',
    '',
    ...lines,
  ].join('\n');
}
